### ISSUE TITLE
why is Kebechet not updating dependencies?

### ISSUE THREAD

**Issue by goern** [AICoE/sesheta#102]
**Describe the bug**
Kebechet is not updating dependencies, I have seen this in some repos cross orgs...

**To Reproduce**
1. Go to https://github.com/AICoE/sesheta/pulls
2. See problem: dependabot is doing the work Kebechet is supposed to do :(

**Expected behavior**
Kebechet keeps the dependencies up to date.

**Screenshots**
![image](https://user-images.githubusercontent.com/260331/112814107-376bf380-907f-11eb-8556-ebfd16df0b5d.png)

**Additional context**
n/a

/kind bug
/priority important-soon
/sig user-experience

**Comment by harshad16** [comment]
This happens due to the reason that kebechet functions on the event from the Github Repository if there are no event on the GitHub repository then it consider that project as stale and don't provide updates.

**Comment by fridex** [comment]
> This happens due to the reason that kebechet functions on the event from the Github Repository if there are no event on the GitHub repository then it consider that project as stale and don't provide updates.

This should be solved with the internal trigger that will trigger the update process on a package release.
