### ISSUE TITLE
approved label added because of... ?!

### ISSUE THREAD

**Issue by goern** [AICoE/sesheta#17]
**Describe the bug**
on https://github.com/thoth-station/core/pull/218#event-2366900200 the approved label is added, I cannot verify why?!

**To Reproduce**
Steps to reproduce the behaviour:
dunno :(

**Expected behaviour**
the approved label is only added when an authorized reviewed approved a PR via an approving github review

**Screenshots**
n/a

**Additional context**
n/a

**Comment by harshad16** [comment]
The Bot `sesheta-approver` which is a cronjob check for positive zuul gate/check (which is check for linting and testing), it adds **approved** label to the PR,if the zuul check is positive.

We could decommission the `sesheta-approver` bot as the `sesheta-webhooks` adds approved label based on the reviewer's review. This should fix this issue.

Thoughts? @goern

**Comment by goern** [comment]
sounds good. let's have labels managed by sesheta-webhooks.

**Comment by harshad16** [comment]
`sesheta-approver` cronjob is suspended.
The job was happy that her fellow :bot: `sesheta-webhook` would handle the good work from now on.
The issue can be closed.

**Comment by goern** [comment]
:heart: that the bots are happy!
