### ISSUE TITLE
add thoth-station/init-job to config

### ISSUE THREAD

**Issue by goern** [AICoE/sesheta#2]
**Is your feature request related to a problem? Please describe.**
https://github.com/thoth-station/init-job/pull/26 has not received an 'approved' label, this seems to be due to the fact that sesheta is not looking at the repo

**Describe the solution you'd like**
add thoth-station/init-job to sesheta's config

**Describe alternatives you've considered**
none.

**Additional context**
n/a

**Comment by harshad16** [comment]
This issue was due to init-job repo write access not granted to sesheta.  
It has been fixed by giving write access to the sesheta for the init-job repo.
The issue can be Closed.
