### ISSUE TITLE
sesheta is not adding `work-in-progress` label when title is stated with WIP

### ISSUE THREAD

**Issue by harshad16** [AICoE/sesheta#23]
**Describe the bug**
The `work-in-progress` label is not added to the pull request even when the title is stated with WIP.

**To Reproduce**
1.  Create a pull request with a title beginning with [WIP].
3. Scroll down to check if sesheta has added `work in progress` label.

**Expected behavior**
If [WIP] or WIP is stated at the beginning of the pull request Title, sesheta should add `work-in-progress` label so that zuul pipeline knows about the work-in-progress.

**Comment by goern** [comment]
hmm... this is a tricky one. we should check if we need that:

1. is WIP github app setting the correct status?
2. can zuul use the WIP status to block merging
3. can zuul use a label to block merging?

if 1 and 2 we are good, if 1 and not 2 and 3 we are good... otherwise we are not good

**Comment by harshad16** [comment]
okay, yes WIP github app is setting the status to WIP and zuul is checking the status to block merge.
I thought the` work-in-progress` label is needed, but zuul doesn't need it, it is able to check the status.
thanks for the informative comment.

**Comment by goern** [comment]
Ah no, is a little more tricky, I think WIP uses a check rater than a status, and zuul can only check for status?! I think there was so fancyness

**Comment by goern** [comment]
can we use the label at https://github.com/thoth-station/zuul-config/blob/master/zuul.d/_pipelines.yaml#L53 so that zuul will not merge?! :)

**Comment by goern** [comment]
see also https://github.com/goern/sesheta-actions/commit/beb8f5c35d4946b7885bf35fe407039f8dd0ef2a

**Comment by harshad16** [comment]
> see also [goern/sesheta-actions@beb8f5c](https://github.com/goern/sesheta-actions/commit/beb8f5c35d4946b7885bf35fe407039f8dd0ef2a)

okay :smile:

**Comment by goern** [comment]
Currently the send to be an issue with authenticating the review manager GitHub app... I'm investigating
