### ISSUE TITLE
Sesheta merged with ```do-not-merge/work-in-progress label```

### ISSUE THREAD

**Issue by pacospace** [AICoE/sesheta#31]
**Describe the bug**
Sesheta merged with ```do-not-merge/work-in-progress label```

**Expected behavior**
PR not merged due to the label.

**Additional context**
Example: https://github.com/thoth-station/graph-sync-job/pull/233

**Comment by harshad16** [comment]
Similar to https://github.com/AICoE/sesheta/issues/23
